version: '3.9'

services:
  atomex_images_flask:
    container_name: atomex_images_flask
    hostname: atomex_images_flask
    build: .
    volumes:
      - ./static:/app/static
    networks:
      - images-net

  atomex_images_nginx:
    container_name: atomex_images_nginx
    image: nginx
    volumes:
      - ./nginx_templates:/etc/nginx/templates
      - ./static:/media
    ports:
      - "8060:80"
    environment:
      - NGINX_PORT=80
    networks:
      - images-net

networks:
  images-net: